name: transmission_api
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/xxzj990/transmission_api

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  colorize: ^3.0.0
  dio: ^5.3.2

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.6
